services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Supseven\Prefetch\DataProcessing\PrefetchProcessor:
    public: true
    arguments:
      $connectionPool: '@TYPO3\CMS\Core\Database\ConnectionPool'
